# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WonderApp' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Push', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTPushNotification'
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS


  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'Firebase'
  pod 'Firebase/Messaging'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNImageRotate', :path => '../node_modules/react-native-image-rotate'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'FBSDKCoreKit'  
  pod 'FBSDKLoginKit'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end

    targets_to_ignore = %w(React yoga)
    if targets_to_ignore.include? target.name
        target.remove_from_project
    end
    
  end
end
